import { Link } from 'react-router-dom';

export const PrivacyPage = () => <main className="mx-auto max-w-3xl space-y-7 px-5 py-10 text-slate-800">
  <Link to="/classes" className="font-semibold text-indigo-700 underline">Về lớp học</Link>
  <h1 className="text-3xl font-bold">Chính sách dữ liệu cá nhân</h1>
  <p>Cập nhật ngày 01/10/2026. Hệ thống lớp học do người vận hành máy chủ này quản lý. Để liên hệ về dữ liệu, gửi yêu cầu trong Hồ sơ của tôi; yêu cầu được lưu và chỉ quản trị nền tảng được xử lý.</p>
  <section className="space-y-3"><h2 className="text-xl font-bold">Dữ liệu và mục đích sử dụng</h2><p>Email, tên, ảnh và hồ sơ phục vụ đăng nhập và hiển thị theo lựa chọn riêng tư của bạn. Thành viên, tiến độ, câu trả lời, điểm, bài đăng và bình luận phục vụ lớp học. Đơn hàng và quyền truy cập phục vụ mua/gia hạn/hoàn tiền. Nhật ký quản trị và trạng thái chống lạm dụng bảo vệ hệ thống.</p><p>Dữ liệu chính được lưu trên máy chủ này; bản sao hoạt động và quan hệ nằm trong MongoDB/Neo4j, tệp trong MinIO. Ảnh ngoài hệ thống chỉ được tải khi hiển thị và có thể gửi địa chỉ IP đến nơi lưu ảnh; ảnh giới thiệu không gửi referrer. Không có cổng thanh toán thật ở phiên bản hiện tại.</p></section>
  <section className="space-y-3"><h2 className="text-xl font-bold">Thời gian lưu trữ</h2><p>Thông tin tài khoản và học tập được giữ trong thời gian sử dụng lớp; yêu cầu xóa được rà soát theo mục đích và căn cứ còn áp dụng. Chứng từ tài chính, kết quả cần giải quyết khiếu nại và nhật ký liên quan không bị xóa tự động chỉ vì đóng tài khoản. Quản trị viên phải ghi rõ căn cứ và thời hạn khi tạm giữ.</p><p>Outbox đã xử lý được dọn sau 7 ngày. Bộ đếm chống lạm dụng hết hạn sau cửa sổ của từng giới hạn. Cookie làm mới có thời hạn tối đa 30 ngày, access token 1 giờ. Chính sách vận hành đặt thời hạn bản sao lưu 30 ngày; việc xóa khỏi hệ thống chính được phản ánh qua vòng đời bản sao lưu và không được phục hồi tài khoản đã đóng khi khôi phục.</p></section>
  <section className="space-y-3"><h2 className="text-xl font-bold">Quyền và cách gửi yêu cầu</h2><p>Trong Hồ sơ của tôi, bạn có thể sửa thông tin, đổi phạm vi hiển thị, tải bản sao dữ liệu hoặc gửi yêu cầu xóa. Tải/xóa yêu cầu mật khẩu hiện tại để xác nhận danh tính. Yêu cầu xóa có trạng thái và kết quả xử lý; nếu cần giữ hồ sơ, quản trị viên giải thích căn cứ. Chủ lớp cần chuyển quyền sở hữu hoặc lưu trữ lớp trước khi đóng tài khoản.</p><p>Đóng tài khoản làm mất quyền đăng nhập và ẩn danh hóa hồ sơ. Nội dung đã chia sẻ, hồ sơ học tập hoặc chứng từ cần giữ được xem xét riêng; đây không phải thao tác xóa tất cả dấu vết tài chính hay nội dung của người khác.</p><Link to="/me/profile" className="inline-block rounded-xl bg-indigo-600 px-4 py-3 font-semibold text-white">Quản lý dữ liệu của tôi</Link></section>
  <section className="space-y-3"><h2 className="text-xl font-bold">Cơ sở chính sách</h2><p>Chính sách vận hành được lập theo mục đích tối thiểu hóa dữ liệu và quyền của chủ thể dữ liệu, tham chiếu <a className="text-indigo-700 underline" href="https://vanban.chinhphu.vn/?classid=1&docid=214590&pageid=27160&typegroup=" rel="noreferrer" target="_blank">Luật Bảo vệ dữ liệu cá nhân 91/2025/QH15</a>. Người vận hành chịu trách nhiệm công bố danh tính/liên hệ, căn cứ xử lý, hồ sơ đánh giá tác động và nghĩa vụ cụ thể trước khi cung cấp dịch vụ cho người dùng bên ngoài.</p></section>
</main>;
